### ISSUE TITLE
CheckM/gtdb-tk tables?

### ISSUE THREAD

**Issue by bcpd** [Hydro3639/NanoPhase#4]
Hi - It would be awesome if `nanophase` allowed for an option to keep the outputs of checkm (run with `-tab_table`) and gtdb -- i.e. the `gtdbtk.*summary.tsv` files. Both are useful for downstream applications. It also looks like the final `genome.summary` table doesn't display species-level information or other useful pieces of information such as ANI, etc.

**Comment by Hydro3639** [comment]
Thanks for your suggestion. I have revised the `nanophase meta` script so that checkm and gtdbtk results were kept in the final output (_path_to_output/03-Polishing/checkm-result_ and _path_to_output/03-Polishing/gtdbtk-result_). The new features will be included in the next conda release (together with other new functions, e.g., checkm1 -> [checkm2](https://github.com/chklovski/CheckM2)), but, currently, I would suggest to replace `nanophase.meta` script with the new one following the instruction below:
```
1) conda activate nanophase ## activate nanophase env
2) wget https://raw.githubusercontent.com/Hydro3639/NanoPhase/main/bin/nanophase.meta -O $(which nanophase.meta) && chmod +x $(which nanophase.meta)
```
If you want to generate the above-mentioned results, please remove the folder of `path_to_output/03-Polishing/Final-bins` and the file of `path_to_output/03-Polishing/nanophase.ont.genome.summary` or `path_to_output/03-Polishing/nanophase.hybrid.genome.summary`; then re-run the same command. Please let me know if you need more help.

**Comment by bcpd** [comment]
Great - thank you.

**Comment by bcpd** [comment]
Thanks again for the updates. I did run into the following issue (it was not happening with v. 0.2.2):
`fastANI: error while loading shared libraries: libopenblas.so.0: cannot open shared object file`

This is a fairly generic error with not straightforward solution. Have you seen this?

**Comment by Hydro3639** [comment]
Sorry to hear you have such an error.

Exactly, I have seen this once on one of our servers before. I am not sure if you can try installing _libopenblas-base_ using command: `sudo apt-get install libopenblas-base` (require sudo). You can simply check by "fastANI -h" to see if you still have this error. 

If it cannot solve your issue or you do not have sudo permission, you may uninstall fastANI and re-install it manually. (Sorry for all these manually things)
```
## remove fastANI
rm -rf $(which fastANI)
## download fastANI binary file
wget https://github.com/ParBLiSS/FastANI/releases/download/v1.33/fastANI-Linux64-v1.33.zip
## unzip
unzip -d $(dirname $(which nanophase)) fastANI-Linux64-v1.33.zip
## check
fastANI -h
```
Please let me know if it works.

**Comment by bcpd** [comment]
Installing the library (within the environment) worked; thank you! (The `checkm-result` folder does not have the `checkm_results.tsv` file, however; is it stored somewhere else?)

**Comment by Hydro3639** [comment]
Good to hear you have fixed this error.

If you want to have the full result of checkm, it is quite easy to re-generate it using the following command as you have _checkm-result_ folder
```
checkm qa checkm-result/lineage.ms checkm-result/
```
It should be finished in 1-2 mins. I have revised the `nanophase meta` script, and you can update it [as described above](https://github.com/Hydro3639/NanoPhase/issues/4#issuecomment-1374911959), then you don't need to re-run this `qa` command manually in the next time. And the `checkm_results.tsv` file should be in _checkm-result_ folder.

**Comment by bcpd** [comment]
Excelent - thank you.
