### ISSUE TITLE
Issues with Installation

### ISSUE THREAD

**Issue by bferro12** [Hydro3639/NanoPhase#6]
Hello,

I am currently running into issues with the installation of NanoPhase and some of its dependencies. I have attached files containing the full bash inputs/outputs, though here are some of the notable errors:

- During mamba install:
- nanophase 0.2.2**  does not exist (perhaps a typo or a missing channel). 
- - Note: Process stops after this occurrence.

- During git clone install using `Install.sh`:
- masurca 4.0.9**  does not exist (perhaps a typo or a missing channel).
- medaka 1.6.0**  does not exist (perhaps a typo or a missing channel).
- pplacer   does not exist (perhaps a typo or a missing channel).
- Collecting pysam>=0.19.0
  Using cached pysam-0.20.0.tar.gz (4.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  python setup.py egg_info did not run successfully.
- configure: error: liblzma development files not found
- Building wheel for numpy (pyproject.toml) ... error
- ERROR: Failed building wheel for numpy
- ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

I am currently working on a Intel x86 64-bit MacBook Pro, but have the goal to create this on the Apple M1 ARM 64-bit Mac. Would this possibly lead to an issue with how conda works, leading to the current issue at hand?

Thank you in advance!

[nanophase_mamba_install_fail.txt](https://github.com/Hydro3639/NanoPhase/files/11065553/nanophase_mamba_install_fail.txt)
[nanophase_git_install_fail.txt](https://github.com/Hydro3639/NanoPhase/files/11065555/nanophase_git_install_fail.txt)

**Comment by Hydro3639** [comment]
Hello,

Thank you for your interest in Nanophase. Unfortunately, we regret to say that Nanophase cannot be installed on macOS systems due to difficulties with automatically installing some of the packages that are integrated into the tool. But you can try installing all [packages](https://github.com/Hydro3639/NanoPhase/blob/main/dependancy.md) by yourself and run nanophase-relevant commands.

I would not recommend it unless you are very familiar with the environmental configuration and all the dependencies.  Therefore, trying nanophase on Linux (e.g., Ubuntu) might be an easier solution.

Best

**Comment by bferro12** [comment]
Thank you for your quick response! After seeing your suggestion, I was able to get it running on Ubuntu. I will close this issue, thank you again!
